name: Examples

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]
        python-version: [3.7]
        example:
          - "examples/arduino-blink"
          - "examples/arduino-external-libs"
          - "examples/arduino-internal-libs"
          - "examples/native-blink"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/platformio/platformio/archive/develop.zip
          pip install -U shutils pathlib bs4 zipfile2 six
          platformio platform install file://.
          platformio run -d examples/native-blink -e AVR128DA48 -t fixtoolchain
#          python .github/patchtoolchain.py
      - name: Build examples
        run: |
          platformio run -d ${{ matrix.example }}
